_common: !include ../../package.common.yaml
<<: *common
<<: *flags

name: drvgraph
version: 0.1.0.0

dependencies:
  - ansi-terminal
  - base
  - bytestring
  - containers
  - directory
  - dlist
  - filepath
  - megaparsec
  - mtl
  - optics
  - text
  - transformers

library:
  source-dirs: src

executables:
  drvgraph:
    source-dirs: app
    main: Main.hs
    dependencies:
      - drvgraph

tests:
  test:
    source-dirs: test
    main: Spec.hs
    dependencies:
      - drvgraph
      - file-embed
      - hedgehog
      - tasty
      - tasty-hedgehog
      - tasty-hunit
    ghc-options: *test-ghc-options
    when:
      - condition: "!flag(in-nix-shell)"
        build-tools:
          - tasty-discover:tasty-discover
